name: Spider

on:
  workflow_dispatch:

jobs:
  spider:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: 'Set up Python'
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Run a single-line script
      run: |
        pip install requests
        pip install lxml
        pip install scrapy
        scrapy crawl picture

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: img
        path: image
